// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fisher_scoring_qr_step_mask
Eigen::MatrixXd fisher_scoring_qr_step_mask(const Eigen::Map<Eigen::MatrixXd>& model_matrix, const Eigen::Map<Eigen::VectorXd>& counts, const Eigen::Map<Eigen::VectorXd>& mu, const Eigen::Map<Eigen::VectorXd>& theta_times_mu);
RcppExport SEXP _glmGamPoi2_fisher_scoring_qr_step_mask(SEXP model_matrixSEXP, SEXP countsSEXP, SEXP muSEXP, SEXP theta_times_muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type theta_times_mu(theta_times_muSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher_scoring_qr_step_mask(model_matrix, counts, mu, theta_times_mu));
    return rcpp_result_gen;
END_RCPP
}
// fisher_scoring_qr_ridge_step_mask
Eigen::MatrixXd fisher_scoring_qr_ridge_step_mask(const Eigen::Map<Eigen::MatrixXd>& model_matrix, const Eigen::Map<Eigen::VectorXd>& counts, const Eigen::Map<Eigen::VectorXd>& mu, const Eigen::Map<Eigen::VectorXd>& theta_times_mu, const Eigen::Map<Eigen::MatrixXd>& ridge_penalty, const Eigen::Map<Eigen::VectorXd>& ridge_target, const Eigen::Map<Eigen::VectorXd>& beta_hat);
RcppExport SEXP _glmGamPoi2_fisher_scoring_qr_ridge_step_mask(SEXP model_matrixSEXP, SEXP countsSEXP, SEXP muSEXP, SEXP theta_times_muSEXP, SEXP ridge_penaltySEXP, SEXP ridge_targetSEXP, SEXP beta_hatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type theta_times_mu(theta_times_muSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type ridge_penalty(ridge_penaltySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type ridge_target(ridge_targetSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type beta_hat(beta_hatSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher_scoring_qr_ridge_step_mask(model_matrix, counts, mu, theta_times_mu, ridge_penalty, ridge_target, beta_hat));
    return rcpp_result_gen;
END_RCPP
}
// fisher_scoring_diagonal_step_mask
Eigen::MatrixXd fisher_scoring_diagonal_step_mask(const Eigen::Map<Eigen::MatrixXd>& model_matrix, const Eigen::Map<Eigen::VectorXd>& counts, const Eigen::Map<Eigen::VectorXd>& mu, const Eigen::Map<Eigen::VectorXd>& theta_times_mu);
RcppExport SEXP _glmGamPoi2_fisher_scoring_diagonal_step_mask(SEXP model_matrixSEXP, SEXP countsSEXP, SEXP muSEXP, SEXP theta_times_muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type theta_times_mu(theta_times_muSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher_scoring_diagonal_step_mask(model_matrix, counts, mu, theta_times_mu));
    return rcpp_result_gen;
END_RCPP
}
// lte_n_equal_rows
bool lte_n_equal_rows(const NumericMatrix& matrix, const int n, const double tolerance);
RcppExport SEXP _glmGamPoi2_lte_n_equal_rows(SEXP matrixSEXP, SEXP nSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(lte_n_equal_rows(matrix, n, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// get_row_groups
IntegerVector get_row_groups(const NumericMatrix& matrix, const int n_groups, const double tolerance);
RcppExport SEXP _glmGamPoi2_get_row_groups(SEXP matrixSEXP, SEXP n_groupsSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< const int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(get_row_groups(matrix, n_groups, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// fitBeta_fisher_scoring
List fitBeta_fisher_scoring(const RObject Y, const Eigen::Map<Eigen::MatrixXd> model_matrix, const RObject exp_offset_matrix, const NumericVector thetas, const Eigen::Map<Eigen::MatrixXd>& beta_mat_v, const Nullable<NumericMatrix> ridge_penalty_nl, const double tolerance, const double max_rel_mu_change, const int max_iter, const bool try_recov_w_optim, const int do_parallel);
RcppExport SEXP _glmGamPoi2_fitBeta_fisher_scoring(SEXP YSEXP, SEXP model_matrixSEXP, SEXP exp_offset_matrixSEXP, SEXP thetasSEXP, SEXP beta_mat_vSEXP, SEXP ridge_penalty_nlSEXP, SEXP toleranceSEXP, SEXP max_rel_mu_changeSEXP, SEXP max_iterSEXP, SEXP try_recov_w_optimSEXP, SEXP do_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const RObject >::type exp_offset_matrix(exp_offset_matrixSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type thetas(thetasSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type beta_mat_v(beta_mat_vSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericMatrix> >::type ridge_penalty_nl(ridge_penalty_nlSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const double >::type max_rel_mu_change(max_rel_mu_changeSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const bool >::type try_recov_w_optim(try_recov_w_optimSEXP);
    Rcpp::traits::input_parameter< const int >::type do_parallel(do_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(fitBeta_fisher_scoring(Y, model_matrix, exp_offset_matrix, thetas, beta_mat_v, ridge_penalty_nl, tolerance, max_rel_mu_change, max_iter, try_recov_w_optim, do_parallel));
    return rcpp_result_gen;
END_RCPP
}
// fitBeta_diagonal_fisher_scoring
List fitBeta_diagonal_fisher_scoring(const RObject Y, const Eigen::Map<Eigen::MatrixXd> model_matrix, const RObject exp_offset_matrix, const NumericVector thetas, const Eigen::Map<Eigen::MatrixXd>& beta_mat_v, const double tolerance, const double max_rel_mu_change, const int max_iter, const bool try_recov_w_optim, const int do_parallel);
RcppExport SEXP _glmGamPoi2_fitBeta_diagonal_fisher_scoring(SEXP YSEXP, SEXP model_matrixSEXP, SEXP exp_offset_matrixSEXP, SEXP thetasSEXP, SEXP beta_mat_vSEXP, SEXP toleranceSEXP, SEXP max_rel_mu_changeSEXP, SEXP max_iterSEXP, SEXP try_recov_w_optimSEXP, SEXP do_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const RObject >::type exp_offset_matrix(exp_offset_matrixSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type thetas(thetasSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type beta_mat_v(beta_mat_vSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const double >::type max_rel_mu_change(max_rel_mu_changeSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const bool >::type try_recov_w_optim(try_recov_w_optimSEXP);
    Rcpp::traits::input_parameter< const int >::type do_parallel(do_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(fitBeta_diagonal_fisher_scoring(Y, model_matrix, exp_offset_matrix, thetas, beta_mat_v, tolerance, max_rel_mu_change, max_iter, try_recov_w_optim, do_parallel));
    return rcpp_result_gen;
END_RCPP
}
// fitBeta_optim
List fitBeta_optim(const RObject Y, const Eigen::Map<Eigen::MatrixXd>& model_matrix, const RObject exp_offset_matrix, const NumericVector thetas, const Eigen::Map<Eigen::MatrixXd>& beta_mat_v, const Nullable<NumericMatrix> ridge_penalty_nl, const int max_iter, const int do_parallel);
RcppExport SEXP _glmGamPoi2_fitBeta_optim(SEXP YSEXP, SEXP model_matrixSEXP, SEXP exp_offset_matrixSEXP, SEXP thetasSEXP, SEXP beta_mat_vSEXP, SEXP ridge_penalty_nlSEXP, SEXP max_iterSEXP, SEXP do_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const RObject >::type exp_offset_matrix(exp_offset_matrixSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type thetas(thetasSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type beta_mat_v(beta_mat_vSEXP);
    Rcpp::traits::input_parameter< const Nullable<NumericMatrix> >::type ridge_penalty_nl(ridge_penalty_nlSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type do_parallel(do_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(fitBeta_optim(Y, model_matrix, exp_offset_matrix, thetas, beta_mat_v, ridge_penalty_nl, max_iter, do_parallel));
    return rcpp_result_gen;
END_RCPP
}
// fitBeta_one_group
List fitBeta_one_group(const RObject Y, const RObject offset_matrix, const NumericVector thetas, const NumericVector beta_start_values, const double tolerance, const int max_iter, const int do_parallel);
RcppExport SEXP _glmGamPoi2_fitBeta_one_group(SEXP YSEXP, SEXP offset_matrixSEXP, SEXP thetasSEXP, SEXP beta_start_valuesSEXP, SEXP toleranceSEXP, SEXP max_iterSEXP, SEXP do_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const RObject >::type offset_matrix(offset_matrixSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type thetas(thetasSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type beta_start_values(beta_start_valuesSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type do_parallel(do_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(fitBeta_one_group(Y, offset_matrix, thetas, beta_start_values, tolerance, max_iter, do_parallel));
    return rcpp_result_gen;
END_RCPP
}
// compute_gp_deviance_mask
double compute_gp_deviance_mask(const double y, const double mu, const double theta);
RcppExport SEXP _glmGamPoi2_compute_gp_deviance_mask(SEXP ySEXP, SEXP muSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gp_deviance_mask(y, mu, theta));
    return rcpp_result_gen;
END_RCPP
}
// compute_gp_deviance_sum_mask
double compute_gp_deviance_sum_mask(const NumericVector y, const NumericVector mu, const double theta);
RcppExport SEXP _glmGamPoi2_compute_gp_deviance_sum_mask(SEXP ySEXP, SEXP muSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gp_deviance_sum_mask(y, mu, theta));
    return rcpp_result_gen;
END_RCPP
}
// compute_gp_deviance_residuals_matrix_mask
Eigen::MatrixXd compute_gp_deviance_residuals_matrix_mask(const SEXP Y_SEXP, const Eigen::Map<Eigen::MatrixXd>& Mu, const Eigen::Map<Eigen::MatrixXd>& thetas);
RcppExport SEXP _glmGamPoi2_compute_gp_deviance_residuals_matrix_mask(SEXP Y_SEXPSEXP, SEXP MuSEXP, SEXP thetasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type Y_SEXP(Y_SEXPSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type thetas(thetasSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_gp_deviance_residuals_matrix_mask(Y_SEXP, Mu, thetas));
    return rcpp_result_gen;
END_RCPP
}
// make_table_if_small
List make_table_if_small(const NumericVector x, size_t stop_if_larger);
RcppExport SEXP _glmGamPoi2_make_table_if_small(SEXP xSEXP, SEXP stop_if_largerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type stop_if_larger(stop_if_largerSEXP);
    rcpp_result_gen = Rcpp::wrap(make_table_if_small(x, stop_if_larger));
    return rcpp_result_gen;
END_RCPP
}
// conventional_loglikelihood_fast
double conventional_loglikelihood_fast(const NumericVector y, const Eigen::Map<Eigen::VectorXd>& mu, double log_theta, const Eigen::Map<Eigen::MatrixXd>& model_matrix, bool do_cr_adj, NumericVector unique_counts, NumericVector count_frequencies);
RcppExport SEXP _glmGamPoi2_conventional_loglikelihood_fast(SEXP ySEXP, SEXP muSEXP, SEXP log_thetaSEXP, SEXP model_matrixSEXP, SEXP do_cr_adjSEXP, SEXP unique_countsSEXP, SEXP count_frequenciesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type log_theta(log_thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< bool >::type do_cr_adj(do_cr_adjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique_counts(unique_countsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type count_frequencies(count_frequenciesSEXP);
    rcpp_result_gen = Rcpp::wrap(conventional_loglikelihood_fast(y, mu, log_theta, model_matrix, do_cr_adj, unique_counts, count_frequencies));
    return rcpp_result_gen;
END_RCPP
}
// conventional_score_function_fast
double conventional_score_function_fast(const NumericVector y, const Eigen::Map<Eigen::VectorXd>& mu, double log_theta, const Eigen::Map<Eigen::MatrixXd>& model_matrix, bool do_cr_adj, NumericVector unique_counts, NumericVector count_frequencies);
RcppExport SEXP _glmGamPoi2_conventional_score_function_fast(SEXP ySEXP, SEXP muSEXP, SEXP log_thetaSEXP, SEXP model_matrixSEXP, SEXP do_cr_adjSEXP, SEXP unique_countsSEXP, SEXP count_frequenciesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type log_theta(log_thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< bool >::type do_cr_adj(do_cr_adjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type unique_counts(unique_countsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type count_frequencies(count_frequenciesSEXP);
    rcpp_result_gen = Rcpp::wrap(conventional_score_function_fast(y, mu, log_theta, model_matrix, do_cr_adj, unique_counts, count_frequencies));
    return rcpp_result_gen;
END_RCPP
}
// conventional_deriv_score_function_fast
double conventional_deriv_score_function_fast(const NumericVector y, const Eigen::Map<Eigen::VectorXd>& mu, double log_theta, const Eigen::Map<Eigen::MatrixXd>& model_matrix, bool do_cr_adj, const NumericVector unique_counts, const NumericVector count_frequencies);
RcppExport SEXP _glmGamPoi2_conventional_deriv_score_function_fast(SEXP ySEXP, SEXP muSEXP, SEXP log_thetaSEXP, SEXP model_matrixSEXP, SEXP do_cr_adjSEXP, SEXP unique_countsSEXP, SEXP count_frequenciesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type log_theta(log_thetaSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< bool >::type do_cr_adj(do_cr_adjSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type unique_counts(unique_countsSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type count_frequencies(count_frequenciesSEXP);
    rcpp_result_gen = Rcpp::wrap(conventional_deriv_score_function_fast(y, mu, log_theta, model_matrix, do_cr_adj, unique_counts, count_frequencies));
    return rcpp_result_gen;
END_RCPP
}
// NR_overdispersion_mle
List NR_overdispersion_mle(const NumericVector y, const Eigen::Map<Eigen::VectorXd>& mu_vector, const Eigen::Map<Eigen::MatrixXd>& model_matrix, const bool do_cox_reid_adjustment, const int max_iter, const double tolerance);
RcppExport SEXP _glmGamPoi2_NR_overdispersion_mle(SEXP ySEXP, SEXP mu_vectorSEXP, SEXP model_matrixSEXP, SEXP do_cox_reid_adjustmentSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type mu_vector(mu_vectorSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_cox_reid_adjustment(do_cox_reid_adjustmentSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(NR_overdispersion_mle(y, mu_vector, model_matrix, do_cox_reid_adjustment, max_iter, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// estimate_overdispersions_fast
List estimate_overdispersions_fast(const RObject Y, const RObject mean_matrix, const NumericMatrix model_matrix, const bool do_cox_reid_adjustment, const double n_subsamples, const int max_iter);
RcppExport SEXP _glmGamPoi2_estimate_overdispersions_fast(SEXP YSEXP, SEXP mean_matrixSEXP, SEXP model_matrixSEXP, SEXP do_cox_reid_adjustmentSEXP, SEXP n_subsamplesSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const RObject >::type mean_matrix(mean_matrixSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_cox_reid_adjustment(do_cox_reid_adjustmentSEXP);
    Rcpp::traits::input_parameter< const double >::type n_subsamples(n_subsamplesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_overdispersions_fast(Y, mean_matrix, model_matrix, do_cox_reid_adjustment, n_subsamples, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// estimate_overdispersions_fast_delayed
List estimate_overdispersions_fast_delayed(const RObject Y, const NumericMatrix model_matrix, const RObject offset_matrix, const Eigen::Map<Eigen::MatrixXd>& beta_mat_v, const bool do_cox_reid_adjustment, const size_t n_subsamples, const int max_iter);
RcppExport SEXP _glmGamPoi2_estimate_overdispersions_fast_delayed(SEXP YSEXP, SEXP model_matrixSEXP, SEXP offset_matrixSEXP, SEXP beta_mat_vSEXP, SEXP do_cox_reid_adjustmentSEXP, SEXP n_subsamplesSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const RObject >::type offset_matrix(offset_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type beta_mat_v(beta_mat_vSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_cox_reid_adjustment(do_cox_reid_adjustmentSEXP);
    Rcpp::traits::input_parameter< const size_t >::type n_subsamples(n_subsamplesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_overdispersions_fast_delayed(Y, model_matrix, offset_matrix, beta_mat_v, do_cox_reid_adjustment, n_subsamples, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// estimate_global_overdispersions_fast
NumericVector estimate_global_overdispersions_fast(const RObject Y, const RObject mean_matrix, const Eigen::Map<Eigen::MatrixXd>& model_matrix, const bool do_cox_reid_adjustment, const NumericVector log_thetas, const int do_parallel);
RcppExport SEXP _glmGamPoi2_estimate_global_overdispersions_fast(SEXP YSEXP, SEXP mean_matrixSEXP, SEXP model_matrixSEXP, SEXP do_cox_reid_adjustmentSEXP, SEXP log_thetasSEXP, SEXP do_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const RObject >::type mean_matrix(mean_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_cox_reid_adjustment(do_cox_reid_adjustmentSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type log_thetas(log_thetasSEXP);
    Rcpp::traits::input_parameter< const int >::type do_parallel(do_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_global_overdispersions_fast(Y, mean_matrix, model_matrix, do_cox_reid_adjustment, log_thetas, do_parallel));
    return rcpp_result_gen;
END_RCPP
}
// estimate_global_overdispersions_fast_delayed
NumericVector estimate_global_overdispersions_fast_delayed(const RObject Y, const Eigen::Map<Eigen::MatrixXd>& model_matrix, const RObject offset_matrix, const Eigen::Map<Eigen::MatrixXd>& beta_mat_v, const bool do_cox_reid_adjustment, const NumericVector log_thetas, const int do_parallel);
RcppExport SEXP _glmGamPoi2_estimate_global_overdispersions_fast_delayed(SEXP YSEXP, SEXP model_matrixSEXP, SEXP offset_matrixSEXP, SEXP beta_mat_vSEXP, SEXP do_cox_reid_adjustmentSEXP, SEXP log_thetasSEXP, SEXP do_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const RObject >::type offset_matrix(offset_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type beta_mat_v(beta_mat_vSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_cox_reid_adjustment(do_cox_reid_adjustmentSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type log_thetas(log_thetasSEXP);
    Rcpp::traits::input_parameter< const int >::type do_parallel(do_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_global_overdispersions_fast_delayed(Y, model_matrix, offset_matrix, beta_mat_v, do_cox_reid_adjustment, log_thetas, do_parallel));
    return rcpp_result_gen;
END_RCPP
}
// estimate_overdispersions_nr_fast
List estimate_overdispersions_nr_fast(const RObject Y, const RObject mean_matrix, const Eigen::Map<Eigen::MatrixXd>& model_matrix, const bool do_cox_reid_adjustment, const size_t n_subsamples, const int max_iter, const double tolerance, const int do_parallel);
RcppExport SEXP _glmGamPoi2_estimate_overdispersions_nr_fast(SEXP YSEXP, SEXP mean_matrixSEXP, SEXP model_matrixSEXP, SEXP do_cox_reid_adjustmentSEXP, SEXP n_subsamplesSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP, SEXP do_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const RObject >::type mean_matrix(mean_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_cox_reid_adjustment(do_cox_reid_adjustmentSEXP);
    Rcpp::traits::input_parameter< const size_t >::type n_subsamples(n_subsamplesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type do_parallel(do_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_overdispersions_nr_fast(Y, mean_matrix, model_matrix, do_cox_reid_adjustment, n_subsamples, max_iter, tolerance, do_parallel));
    return rcpp_result_gen;
END_RCPP
}
// estimate_overdispersions_nr_fast_delayed
List estimate_overdispersions_nr_fast_delayed(const RObject Y, const Eigen::Map<Eigen::MatrixXd>& model_matrix, const RObject offset_matrix, const Eigen::Map<Eigen::MatrixXd>& beta_mat_v, const bool do_cox_reid_adjustment, const size_t n_subsamples, const int max_iter, const double tolerance, const int do_parallel);
RcppExport SEXP _glmGamPoi2_estimate_overdispersions_nr_fast_delayed(SEXP YSEXP, SEXP model_matrixSEXP, SEXP offset_matrixSEXP, SEXP beta_mat_vSEXP, SEXP do_cox_reid_adjustmentSEXP, SEXP n_subsamplesSEXP, SEXP max_iterSEXP, SEXP toleranceSEXP, SEXP do_parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const RObject >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type model_matrix(model_matrixSEXP);
    Rcpp::traits::input_parameter< const RObject >::type offset_matrix(offset_matrixSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type beta_mat_v(beta_mat_vSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_cox_reid_adjustment(do_cox_reid_adjustmentSEXP);
    Rcpp::traits::input_parameter< const size_t >::type n_subsamples(n_subsamplesSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< const int >::type do_parallel(do_parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_overdispersions_nr_fast_delayed(Y, model_matrix, offset_matrix, beta_mat_v, do_cox_reid_adjustment, n_subsamples, max_iter, tolerance, do_parallel));
    return rcpp_result_gen;
END_RCPP
}
// div_zbz_dbl
NumericVector div_zbz_dbl(const NumericVector a, const NumericVector b);
RcppExport SEXP _glmGamPoi2_div_zbz_dbl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(div_zbz_dbl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// div_zbz_int
NumericVector div_zbz_int(const IntegerVector a, const IntegerVector b);
RcppExport SEXP _glmGamPoi2_div_zbz_int(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const IntegerVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(div_zbz_int(a, b));
    return rcpp_result_gen;
END_RCPP
}
// div_zbz_dbl_mat
NumericMatrix div_zbz_dbl_mat(const NumericMatrix a, const NumericMatrix b);
RcppExport SEXP _glmGamPoi2_div_zbz_dbl_mat(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(div_zbz_dbl_mat(a, b));
    return rcpp_result_gen;
END_RCPP
}
// div_zbz_int_mat
NumericMatrix div_zbz_int_mat(const IntegerMatrix a, const IntegerMatrix b);
RcppExport SEXP _glmGamPoi2_div_zbz_int_mat(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(div_zbz_int_mat(a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glmGamPoi2_fisher_scoring_qr_step_mask", (DL_FUNC) &_glmGamPoi2_fisher_scoring_qr_step_mask, 4},
    {"_glmGamPoi2_fisher_scoring_qr_ridge_step_mask", (DL_FUNC) &_glmGamPoi2_fisher_scoring_qr_ridge_step_mask, 7},
    {"_glmGamPoi2_fisher_scoring_diagonal_step_mask", (DL_FUNC) &_glmGamPoi2_fisher_scoring_diagonal_step_mask, 4},
    {"_glmGamPoi2_lte_n_equal_rows", (DL_FUNC) &_glmGamPoi2_lte_n_equal_rows, 3},
    {"_glmGamPoi2_get_row_groups", (DL_FUNC) &_glmGamPoi2_get_row_groups, 3},
    {"_glmGamPoi2_fitBeta_fisher_scoring", (DL_FUNC) &_glmGamPoi2_fitBeta_fisher_scoring, 11},
    {"_glmGamPoi2_fitBeta_diagonal_fisher_scoring", (DL_FUNC) &_glmGamPoi2_fitBeta_diagonal_fisher_scoring, 10},
    {"_glmGamPoi2_fitBeta_optim", (DL_FUNC) &_glmGamPoi2_fitBeta_optim, 8},
    {"_glmGamPoi2_fitBeta_one_group", (DL_FUNC) &_glmGamPoi2_fitBeta_one_group, 7},
    {"_glmGamPoi2_compute_gp_deviance_mask", (DL_FUNC) &_glmGamPoi2_compute_gp_deviance_mask, 3},
    {"_glmGamPoi2_compute_gp_deviance_sum_mask", (DL_FUNC) &_glmGamPoi2_compute_gp_deviance_sum_mask, 3},
    {"_glmGamPoi2_compute_gp_deviance_residuals_matrix_mask", (DL_FUNC) &_glmGamPoi2_compute_gp_deviance_residuals_matrix_mask, 3},
    {"_glmGamPoi2_make_table_if_small", (DL_FUNC) &_glmGamPoi2_make_table_if_small, 2},
    {"_glmGamPoi2_conventional_loglikelihood_fast", (DL_FUNC) &_glmGamPoi2_conventional_loglikelihood_fast, 7},
    {"_glmGamPoi2_conventional_score_function_fast", (DL_FUNC) &_glmGamPoi2_conventional_score_function_fast, 7},
    {"_glmGamPoi2_conventional_deriv_score_function_fast", (DL_FUNC) &_glmGamPoi2_conventional_deriv_score_function_fast, 7},
    {"_glmGamPoi2_NR_overdispersion_mle", (DL_FUNC) &_glmGamPoi2_NR_overdispersion_mle, 6},
    {"_glmGamPoi2_estimate_overdispersions_fast", (DL_FUNC) &_glmGamPoi2_estimate_overdispersions_fast, 6},
    {"_glmGamPoi2_estimate_overdispersions_fast_delayed", (DL_FUNC) &_glmGamPoi2_estimate_overdispersions_fast_delayed, 7},
    {"_glmGamPoi2_estimate_global_overdispersions_fast", (DL_FUNC) &_glmGamPoi2_estimate_global_overdispersions_fast, 6},
    {"_glmGamPoi2_estimate_global_overdispersions_fast_delayed", (DL_FUNC) &_glmGamPoi2_estimate_global_overdispersions_fast_delayed, 7},
    {"_glmGamPoi2_estimate_overdispersions_nr_fast", (DL_FUNC) &_glmGamPoi2_estimate_overdispersions_nr_fast, 8},
    {"_glmGamPoi2_estimate_overdispersions_nr_fast_delayed", (DL_FUNC) &_glmGamPoi2_estimate_overdispersions_nr_fast_delayed, 9},
    {"_glmGamPoi2_div_zbz_dbl", (DL_FUNC) &_glmGamPoi2_div_zbz_dbl, 2},
    {"_glmGamPoi2_div_zbz_int", (DL_FUNC) &_glmGamPoi2_div_zbz_int, 2},
    {"_glmGamPoi2_div_zbz_dbl_mat", (DL_FUNC) &_glmGamPoi2_div_zbz_dbl_mat, 2},
    {"_glmGamPoi2_div_zbz_int_mat", (DL_FUNC) &_glmGamPoi2_div_zbz_int_mat, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_glmGamPoi2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
