# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fisher_scoring_qr_step <- function(model_matrix, counts, mu, theta_times_mu) {
    .Call(`_glmGamPoi2_fisher_scoring_qr_step_mask`, model_matrix, counts, mu, theta_times_mu)
}

fisher_scoring_qr_ridge_step <- function(model_matrix, counts, mu, theta_times_mu, ridge_penalty, ridge_target, beta_hat) {
    .Call(`_glmGamPoi2_fisher_scoring_qr_ridge_step_mask`, model_matrix, counts, mu, theta_times_mu, ridge_penalty, ridge_target, beta_hat)
}

fisher_scoring_diagonal_step <- function(model_matrix, counts, mu, theta_times_mu) {
    .Call(`_glmGamPoi2_fisher_scoring_diagonal_step_mask`, model_matrix, counts, mu, theta_times_mu)
}

lte_n_equal_rows <- function(matrix, n, tolerance = 1e-10) {
    .Call(`_glmGamPoi2_lte_n_equal_rows`, matrix, n, tolerance)
}

get_row_groups <- function(matrix, n_groups, tolerance = 1e-10) {
    .Call(`_glmGamPoi2_get_row_groups`, matrix, n_groups, tolerance)
}

fitBeta_fisher_scoring <- function(Y, model_matrix, exp_offset_matrix, thetas, beta_mat_v, ridge_penalty_nl, tolerance, max_rel_mu_change, max_iter, try_recov_w_optim = FALSE, do_parallel = 0L) {
    .Call(`_glmGamPoi2_fitBeta_fisher_scoring`, Y, model_matrix, exp_offset_matrix, thetas, beta_mat_v, ridge_penalty_nl, tolerance, max_rel_mu_change, max_iter, try_recov_w_optim, do_parallel)
}

fitBeta_diagonal_fisher_scoring <- function(Y, model_matrix, exp_offset_matrix, thetas, beta_mat_v, tolerance, max_rel_mu_change, max_iter, try_recov_w_optim = FALSE, do_parallel = 0L) {
    .Call(`_glmGamPoi2_fitBeta_diagonal_fisher_scoring`, Y, model_matrix, exp_offset_matrix, thetas, beta_mat_v, tolerance, max_rel_mu_change, max_iter, try_recov_w_optim, do_parallel)
}

fitBeta_optim <- function(Y, model_matrix, exp_offset_matrix, thetas, beta_mat_v, ridge_penalty_nl, max_iter, do_parallel = 0L) {
    .Call(`_glmGamPoi2_fitBeta_optim`, Y, model_matrix, exp_offset_matrix, thetas, beta_mat_v, ridge_penalty_nl, max_iter, do_parallel)
}

fitBeta_one_group <- function(Y, offset_matrix, thetas, beta_start_values, tolerance, max_iter, do_parallel = 0L) {
    .Call(`_glmGamPoi2_fitBeta_one_group`, Y, offset_matrix, thetas, beta_start_values, tolerance, max_iter, do_parallel)
}

compute_gp_deviance <- function(y, mu, theta) {
    .Call(`_glmGamPoi2_compute_gp_deviance_mask`, y, mu, theta)
}

compute_gp_deviance_sum <- function(y, mu, theta) {
    .Call(`_glmGamPoi2_compute_gp_deviance_sum_mask`, y, mu, theta)
}

compute_gp_deviance_residuals_matrix <- function(Y_SEXP, Mu, thetas) {
    .Call(`_glmGamPoi2_compute_gp_deviance_residuals_matrix_mask`, Y_SEXP, Mu, thetas)
}

make_table_if_small <- function(x, stop_if_larger) {
    .Call(`_glmGamPoi2_make_table_if_small`, x, stop_if_larger)
}

conventional_loglikelihood_fast <- function(y, mu, log_theta, model_matrix, do_cr_adj, unique_counts = as.numeric( c()), count_frequencies = as.numeric( c())) {
    .Call(`_glmGamPoi2_conventional_loglikelihood_fast`, y, mu, log_theta, model_matrix, do_cr_adj, unique_counts, count_frequencies)
}

conventional_score_function_fast <- function(y, mu, log_theta, model_matrix, do_cr_adj, unique_counts = as.numeric( c()), count_frequencies = as.numeric( c())) {
    .Call(`_glmGamPoi2_conventional_score_function_fast`, y, mu, log_theta, model_matrix, do_cr_adj, unique_counts, count_frequencies)
}

conventional_deriv_score_function_fast <- function(y, mu, log_theta, model_matrix, do_cr_adj, unique_counts = as.numeric( c()), count_frequencies = as.numeric( c())) {
    .Call(`_glmGamPoi2_conventional_deriv_score_function_fast`, y, mu, log_theta, model_matrix, do_cr_adj, unique_counts, count_frequencies)
}

NR_overdispersion_mle <- function(y, mu_vector, model_matrix, do_cox_reid_adjustment, max_iter, tolerance = 1e-8) {
    .Call(`_glmGamPoi2_NR_overdispersion_mle`, y, mu_vector, model_matrix, do_cox_reid_adjustment, max_iter, tolerance)
}

estimate_overdispersions_fast <- function(Y, mean_matrix, model_matrix, do_cox_reid_adjustment, n_subsamples, max_iter) {
    .Call(`_glmGamPoi2_estimate_overdispersions_fast`, Y, mean_matrix, model_matrix, do_cox_reid_adjustment, n_subsamples, max_iter)
}

estimate_overdispersions_fast_delayed <- function(Y, model_matrix, offset_matrix, beta_mat_v, do_cox_reid_adjustment, n_subsamples, max_iter) {
    .Call(`_glmGamPoi2_estimate_overdispersions_fast_delayed`, Y, model_matrix, offset_matrix, beta_mat_v, do_cox_reid_adjustment, n_subsamples, max_iter)
}

estimate_global_overdispersions_fast <- function(Y, mean_matrix, model_matrix, do_cox_reid_adjustment, log_thetas, do_parallel = 0L) {
    .Call(`_glmGamPoi2_estimate_global_overdispersions_fast`, Y, mean_matrix, model_matrix, do_cox_reid_adjustment, log_thetas, do_parallel)
}

estimate_global_overdispersions_fast_delayed <- function(Y, model_matrix, offset_matrix, beta_mat_v, do_cox_reid_adjustment, log_thetas, do_parallel = 0L) {
    .Call(`_glmGamPoi2_estimate_global_overdispersions_fast_delayed`, Y, model_matrix, offset_matrix, beta_mat_v, do_cox_reid_adjustment, log_thetas, do_parallel)
}

estimate_overdispersions_nr_fast <- function(Y, mean_matrix, model_matrix, do_cox_reid_adjustment, n_subsamples, max_iter, tolerance = 1e-8, do_parallel = 0L) {
    .Call(`_glmGamPoi2_estimate_overdispersions_nr_fast`, Y, mean_matrix, model_matrix, do_cox_reid_adjustment, n_subsamples, max_iter, tolerance, do_parallel)
}

estimate_overdispersions_nr_fast_delayed <- function(Y, model_matrix, offset_matrix, beta_mat_v, do_cox_reid_adjustment, n_subsamples, max_iter, tolerance = 1e-8, do_parallel = 0L) {
    .Call(`_glmGamPoi2_estimate_overdispersions_nr_fast_delayed`, Y, model_matrix, offset_matrix, beta_mat_v, do_cox_reid_adjustment, n_subsamples, max_iter, tolerance, do_parallel)
}

div_zbz_dbl <- function(a, b) {
    .Call(`_glmGamPoi2_div_zbz_dbl`, a, b)
}

div_zbz_int <- function(a, b) {
    .Call(`_glmGamPoi2_div_zbz_int`, a, b)
}

div_zbz_dbl_mat <- function(a, b) {
    .Call(`_glmGamPoi2_div_zbz_dbl_mat`, a, b)
}

div_zbz_int_mat <- function(a, b) {
    .Call(`_glmGamPoi2_div_zbz_int_mat`, a, b)
}

