# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeCumSumLookupVector <- function(y) {
    .Call(`_glmGamPoi_makeCumSumLookupVector`, y)
}

score_function_bandara_fast <- function(y, cumsumLookupTable, mu, r, model_matrix, do_cr_adj) {
    .Call(`_glmGamPoi_score_function_bandara_fast`, y, cumsumLookupTable, mu, r, model_matrix, do_cr_adj)
}

score_deriv_function_bandara_fast <- function(y, cumsumLookupTable, mu, theta, model_matrix, do_cr_adj) {
    .Call(`_glmGamPoi_score_deriv_function_bandara_fast`, y, cumsumLookupTable, mu, theta, model_matrix, do_cr_adj)
}

